# Generated by Django 5.1.6 on 2025-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueentrada',
            name='tipo',
            field=models.CharField(choices=[('S', 'SAIDA'), ('E', 'ENTRADA')], default='E', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='estoquesaida',
            name='tipo',
            field=models.CharField(choices=[('S', 'SAIDA'), ('E', 'ENTRADA')], default='S', editable=False, max_length=1),
        ),
    ]
